/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_example_Main */

#ifndef _Included_org_example_Main
#define _Included_org_example_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Main
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_Main_sayHello
  (JNIEnv *, jobject);

/*
 * Class:     org_example_Main
 * Method:    sayHello2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_example_Main_sayHello2
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
